import assert from 'node:assert/strict';
import { randomUUID,randomBytes } from 'node:crypto';
import { mkdir,writeFile } from 'node:fs/promises';
import pg from 'pg';
import { z } from 'zod';
import { accountSchema,metricsSchema } from '../../src/lib/domain';

// Deliberately fixed to this project's isolated local database. No production URL is accepted.
const pool=new pg.Pool({connectionString:'postgresql://postgres:postgres@127.0.0.1:55422/postgres',max:20});
const report:{name:string;passed:boolean;milliseconds:number}[]=[];
const run=randomBytes(4).toString('hex');
const token=()=>randomBytes(32).toString('hex');
async function one(sql:string,values:unknown[]=[]){const result=await pool.query<{value:unknown}>(sql,values);return result.rows[0]?.value;}
async function check(name:string,fn:()=>Promise<void>){const start=Date.now();await fn();report.push({name,passed:true,milliseconds:Date.now()-start});console.log(`PASS ${name}`);}
async function identity(label:string,verified=true){const id=randomUUID(),email=`${label}-${run}@example.test`;await pool.query("insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,created_at,updated_at) values($1,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',$2,case when $3 then now() else null end,now(),now())",[id,email,verified]);return {id,email,token:token(),handle:`${label}_${run}`.slice(0,20)};}
type Fixture=Awaited<ReturnType<typeof identity>>;
async function hold(u:Fixture,invitation='',handle=u.handle){return one("select public.neylo_hold($1,$2,$3,'local-fixture-v1',$4,'direct','database-test',true) as value",[u.token,u.email,handle,invitation]);}
async function finish(u:Fixture,key:string=randomUUID()){return accountSchema.parse(await one('select public.neylo_finalize($1,$2,$3) as value',[u.id,u.token,key]));}
async function account(u:Fixture){return accountSchema.parse(await one('select public.neylo_account($1) as value',[u.id]));}
async function enroll(label:string,invitation=''){const u=await identity(label);await hold(u,invitation);return {user:u,account:await finish(u)};}

try{
  const marker=await one("select current_setting('port')::text as value");assert.equal(marker,'5432');
  await pool.query('truncate public.profiles,public.pending_signups,public.participant_tags,public.admin_memberships,public.admin_audit_log,public.idempotency_records,public.rate_limit_buckets cascade');
  await pool.query("insert into public.campaign_versions(id,welcome_minor,referral_minor,referral_cap,founder_cap,terms_body,privacy_body,eligibility_region,starts_at,published_at) values('local-fixture-v1',10000,5000,3,100,'LOCAL TEST FIXTURE ONLY. No public offer.','LOCAL TEST FIXTURE ONLY.','Local test environment',now()-interval '1 day',now()) on conflict do nothing");
  await pool.query("update public.campaign_state set active_version='local-fixture-v1',paused=false,allocated_founders=0");
  const a=await identity('alpha');
  await check('Unverified attempts and holds do not award credits',async()=>{await hold(a);assert.equal(await one('select count(*)::integer as value from public.credit_entries'),0);});
  let aAccount=await finish(a);
  await check('First eligible verified completion reserves exactly 100 KM',async()=>{assert.equal(aAccount.totalMinor,10000);assert.equal(aAccount.founderOrdinal,1);});
  await check('Twenty concurrent retries yield one account and one welcome grant',async()=>{const responses=await Promise.all(Array.from({length:20},()=>finish(a,'durable-retry-key')));assert.ok(responses.every(r=>r.totalMinor===10000));assert.equal(await one("select count(*)::integer as value from public.credit_entries where beneficiary_id=$1 and source_type='welcome'",[a.id]),1);});
  const b=await identity('bravo');
  await check('Invitation lookup and held signup alone earn no referral reward',async()=>{await one('select public.neylo_invitation($1) as value',[aAccount.inviteCode]);await hold(b,aAccount.inviteCode);assert.equal((await account(a)).totalMinor,10000);});
  await check('Eligible referred verification produces exactly one 50 KM award',async()=>{await Promise.all(Array.from({length:12},()=>finish(b)));aAccount=await account(a);assert.equal(aAccount.totalMinor,15000);assert.equal(aAccount.referralSlots,1);assert.equal(aAccount.referrals.length,1);});
  const friends=await Promise.all(Array.from({length:6},(_,i)=>identity(`friend${i}`)));
  await check('Concurrent referrals enforce the three-friend and 250 KM caps',async()=>{await Promise.all(friends.map(f=>hold(f,aAccount.inviteCode)));await Promise.all(friends.map(f=>finish(f)));const current=await account(a);assert.equal(current.totalMinor,25000);assert.equal(current.referralSlots,3);assert.equal(current.referrals.filter(r=>r.status==='credited').length,3);});
  await pool.query("insert into public.admin_memberships(user_id,role) values($1,'operator')",[a.id]);
  await check('Reversing a welcome entitlement disables invitation reward eligibility',async()=>{
    const founder=await enroll('welcomerev');
    const before=z.object({mayEarn:z.boolean()}).parse(await one('select public.neylo_invitation($1) as value',[founder.account.inviteCode]));assert.equal(before.mayEarn,true);
    const welcome=founder.account.entries.find(entry=>entry.type==='welcome');assert.ok(welcome);
    await one("select public.neylo_reverse($1,$2,'Local welcome eligibility test') as value",[a.id,welcome.id]);
    const after=z.object({mayEarn:z.boolean()}).parse(await one('select public.neylo_invitation($1) as value',[founder.account.inviteCode]));assert.equal(after.mayEarn,false);
    assert.equal((await account(founder.user)).canInviteForReward,false);
  });
  await check('Repeated reversals are immutable and never reopen reward slots',async()=>{const current=await account(a);const grant=current.entries.find(e=>e.type==='referral');assert.ok(grant);const ids=await Promise.all(Array.from({length:8},()=>one("select public.neylo_reverse($1,$2,'Local test correction') as value",[a.id,grant.id])));assert.equal(new Set(ids).size,1);const another=await enroll('afterrev',aAccount.inviteCode);assert.equal(another.account.totalMinor,10000);assert.equal((await account(a)).totalMinor,20000);assert.equal((await account(a)).referralSlots,3);await assert.rejects(()=>pool.query('update public.credit_entries set amount_minor=1 where id=$1',[grant.id]),/IMMUTABLE/);});
  await check('Unverified identity cannot finalize',async()=>{const u=await identity('unverified',false);await hold(u);await assert.rejects(()=>finish(u),/VERIFIED_IDENTITY_REQUIRED/);});
  await check('Verified wrong identity cannot claim another browser hold',async()=>{await assert.rejects(()=>one('select public.neylo_finalize($1,$2,$3) as value',[b.id,a.token,randomUUID()]),/PENDING_IDENTITY_MISMATCH/);});
  await check('Competing handle claims have exactly one winner',async()=>{const users=await Promise.all(Array.from({length:12},(_,i)=>identity(`race${i}`)));const results=await Promise.allSettled(users.map(u=>hold(u,'',`race_${run}`)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
  await check('Expired holds are reclaimed atomically and the original cannot finalize',async()=>{const old=await identity('expired'),fresh=await identity('reclaimed');await hold(old);await pool.query("update public.pending_signups set expires_at=now()-interval '1 minute' where token_hash=$1",[old.token]);await pool.query("update public.handle_registry set expires_at=now()-interval '1 minute' where handle=$1",[old.handle]);await hold(fresh,'',old.handle);await assert.rejects(()=>finish(old),/HOLD_EXPIRED/);assert.equal((await finish(fresh)).handle,old.handle);});
  await check('Self-referrals and repeated enrollment are rejected',async()=>{await assert.rejects(()=>hold({...a,token:token()}),/SIGN_IN_REQUIRED/);await assert.rejects(()=>pool.query("insert into public.referrals(inviter_id,invitee_id,terms_version) values($1,$1,'local-fixture-v1')",[a.id]),/check constraint/);});
  await check('Staff/test accounts are completed but excluded from awards and participant metrics',async()=>{const u=await identity('staffcase');await pool.query("insert into public.participant_tags(email,cohort,reason) values($1,'test','Local test classification')",[u.email]);await hold(u,aAccount.inviteCode);const result=await finish(u);assert.equal(result.totalMinor,0);assert.equal(result.eligibility,'excluded');const all=metricsSchema.parse(await one("select public.neylo_metrics($1,'2026-01-01','2100-01-01','all') as value",[a.id]));const participants=metricsSchema.parse(await one("select public.neylo_metrics($1,'2026-01-01','2100-01-01','participants') as value",[a.id]));assert.equal(all.verifiedCompleted,participants.verifiedCompleted+1);});
  const reviewer=await enroll('reviewhost');
  await check('Review holds referral awards until an audited eligibility decision',async()=>{const u=await identity('reviewcase');await pool.query("insert into public.participant_tags(email,cohort,review_required,reason) values($1,'independent',true,'Local review case')",[u.email]);await hold(u,reviewer.account.inviteCode);assert.equal((await finish(u)).totalMinor,0);assert.equal((await account(reviewer.user)).totalMinor,10000);await one("select public.neylo_review($1,$2,'eligible','Reviewed local fixture') as value",[a.id,u.id]);assert.equal((await account(reviewer.user)).totalMinor,15000);});
  await check('Anonymous and ordinary users cannot invoke privileged RPC or read private attempts',async()=>{const c=await pool.connect();try{await c.query('begin');await c.query('set local role anon');await assert.rejects(()=>c.query('select public.neylo_campaign()'),/permission denied/);await c.query('rollback');await c.query('begin');await c.query('set local role authenticated');await c.query("select set_config('request.jwt.claim.sub',$1,true)",[b.id]);const visible=await c.query('select user_id from public.profiles');assert.deepEqual(visible.rows.map(r=>r.user_id),[b.id]);await assert.rejects(()=>c.query('select * from public.pending_signups'),/permission denied/);await c.query('rollback');}finally{c.release();}await assert.rejects(()=>one('select public.neylo_require_admin($1) as value',[b.id]),/FORBIDDEN/);});
  await check('Presenter can read aggregate metrics but cannot mutate campaign',async()=>{await pool.query("insert into public.admin_memberships(user_id,role) values($1,'presenter')",[b.id]);metricsSchema.parse(await one("select public.neylo_metrics($1,'2026-01-01','2100-01-01') as value",[b.id]));await assert.rejects(()=>one("select public.neylo_pause($1,true,'Test forbidden mutation') as value",[b.id]),/FORBIDDEN/);});
  await check('Pause blocks new completion while existing accounts remain readable',async()=>{const u=await identity('paused');await hold(u);await one("select public.neylo_pause($1,true,'Local pause test') as value",[a.id]);await assert.rejects(()=>finish(u),/CAMPAIGN_PAUSED/);assert.equal((await account(a)).totalMinor,20000);await one("select public.neylo_pause($1,false,'Local resume test') as value",[a.id]);});
  await check('OTP cooldown and durable rate limits remain correct under concurrency',async()=>{const u=await identity('cooldown');await hold(u);const accepted=await Promise.all(Array.from({length:12},()=>one('select public.neylo_request_otp($1) as value',[u.token])));assert.equal(accepted.filter(Boolean).length,1);const allowed=await Promise.all(Array.from({length:30},()=>one("select public.neylo_rate_limit('database-test',5,60) as value")));assert.equal(allowed.filter(Boolean).length,5);});
  await check('One hundred founding slots remain exact under capacity overflow races',async()=>{const candidates=await Promise.all(Array.from({length:115},(_,i)=>identity(`capacity${i}`)));await Promise.all(candidates.map(u=>hold(u)));const completed=await Promise.all(candidates.map(u=>finish(u)));assert.equal(await one('select count(*)::integer as value from public.enrollments where founder_ordinal is not null'),100);assert.equal(await one("select count(*)::integer as value from public.credit_entries where source_type='welcome'"),100);assert.ok(completed.some(v=>v.founderOrdinal===null&&v.totalMinor===0));assert.equal(await one("select allocated_founders as value from public.campaign_state where id='founding'"),100);});
  await check('A new non-founding account still qualifies an existing founder referral',async()=>{const result=await enroll('nonfounder',reviewer.account.inviteCode);assert.equal(result.account.founderOrdinal,null);assert.equal(result.account.totalMinor,0);assert.equal((await account(reviewer.user)).totalMinor,20000);});
  await check('Deletion requests persist without falsely declaring data erased',async()=>{assert.equal(await one('select public.neylo_request_deletion($1) as value',[b.id]),'requested');assert.equal(await one('select public.neylo_request_deletion($1) as value',[b.id]),'requested');await one("select public.neylo_process_deletion($1,$2,'processing','Local operator processing') as value",[a.id,b.id]);assert.equal((await account(b)).deletionStatus,'processing');});
  await check('Ledger, counters, dashboard and finalized handles reconcile',async()=>{const result=z.record(z.string(),z.boolean()).parse(await one('select public.neylo_reconcile($1) as value',[a.id]));assert.ok(Object.values(result).every(Boolean));const m=metricsSchema.parse(await one("select public.neylo_metrics($1,'2026-01-01','2100-01-01','all') as value",[a.id]));assert.equal(m.verifiedCompleted,m.finalizedHandles);assert.equal(m.foundingAccounts,100);assert.equal(m.reservedMinor,m.grantedMinor-m.reversedMinor);assert.ok(!JSON.stringify(m).includes('@example.test'));});
  await pool.query("update public.campaign_state set paused=true");
  await mkdir('test-results',{recursive:true});await writeFile('test-results/database.json',JSON.stringify({environment:'Isolated local Supabase Postgres; synthetic database fixtures, not delivered-email evidence',at:new Date().toISOString(),passed:report.length,tests:report},null,2));
  console.log(`${report.length} database checks passed. Local campaign paused after tests.`);
}catch(error){console.error(error);process.exitCode=1;}finally{await pool.end();}
