'use client';
import { useRef,useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import useSWR from 'swr';
import { ArrowUpRight,Check,Copy,LogOut,QrCode,Share2 } from 'lucide-react';
import { z } from 'zod';
import { IdentityCard } from '@/features/card/identity-card';
import { accountSchema,formatCredit,origin,type Account } from '@/lib/domain';
import { request,okSchema } from '@/lib/client';
import { CurrencyControls,useCreditDisplay } from '@/features/currency/provider';
const QrSheet=dynamic(()=>import('./qr-sheet'),{ssr:false});

export function AccountView({initial,support,justReserved=false}:{initial:Account;support:string|null;justReserved?:boolean}){
  const {display,credit}=useCreditDisplay();
  const previous=useRef(initial.totalMinor);const [notice,setNotice]=useState(justReserved?`@${initial.handle} is reserved. Welcome to NEYLO.`:''),[showQr,setShowQr]=useState(false),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false);
  const {data=initial,error,mutate,isValidating}=useSWR('account',()=>request('account',accountSchema),{fallbackData:initial,refreshInterval:30000,revalidateOnFocus:true,refreshWhenHidden:false,onSuccess:fresh=>{if(fresh.totalMinor>previous.current)setNotice(`Your launch fee credits are now ${credit(fresh.totalMinor)}.`);previous.current=fresh.totalMinor;}});
  const hasCredits=data.entries.length>0;
  const invitation=`${origin}/i/${data.inviteCode}`;
  async function copy(){try{await navigator.clipboard.writeText(invitation);setCopied(true);}catch{setNotice('Open Show invite QR to select and copy your invitation URL.');}}
  async function share(){try{if(navigator.share){await navigator.share({title:'Your name. Your money address.',text:`Join me on NEYLO. Reserve your handle before launch.`,url:invitation});}else await copy();}catch(e){if(e instanceof Error&&e.name!=='AbortError')setNotice('Sharing was unavailable. Copy your invitation or show the QR.');}}
  async function changePreference(analytics:boolean,marketing:boolean){setBusy(true);try{await request('account/preferences',okSchema,{analytics,marketing});await mutate();}catch(e){setNotice(e instanceof Error?e.message:'Unable to update preferences.');}finally{setBusy(false);}}
  async function pilot(value:boolean){setBusy(true);try{await request('account/qualification',okSchema,{pilot:value});await mutate();setNotice(value?'Pilot interest saved. This does not change your credits.':'Pilot interest updated.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to save interest.');}finally{setBusy(false);}}
  async function deleteRequest(){setBusy(true);try{await request('account/deletion',z.object({status:z.string()}),{});await mutate();setNotice('Your deletion request is recorded for the operator. Your account has not yet been deleted.');}catch(e){setNotice(e instanceof Error?e.message:'Unable to record request.');}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{await request('auth/signout',okSchema,{});window.location.assign('/signin');}catch(e){setNotice(e instanceof Error?e.message:'Unable to sign out.');setBusy(false);}}
  return <main id="main" className="account-page"><div className="page-intro"><p className="eyebrow">YOUR EARLY ACCESS</p><h1>A name to call yours.</h1><p>Your NEYLO identity is reserved. We’ll take it from here.</p></div><IdentityCard handle={data.handle} state="reserved" totalMinor={data.totalMinor} quiet={showQr} variant={hasCredits?'credit':'waitlist'}/>
    <div className="account-content"><div className="notice account-notice" role="status">{notice||(hasCredits?'Your previously earned launch credits remain reserved.':'You’re on the waitlist. Your handle is reserved.')}</div>{error&&<p role="alert" className="form-error">Unable to refresh. Showing your last confirmed account. <button className="text-button" onClick={()=>mutate()}>Retry</button></p>}
    {hasCredits&&<><CurrencyControls account/><div className="balance-heading"><div><p>Launch credit reserved</p><strong>{credit(data.totalMinor)}</strong></div><span className="balance-tag">Not available to spend yet</span></div>
    {display.currency!=='BAM'&&<p className="currency-base">Reserved amount: {formatCredit(data.totalMinor)} · display equivalent in {display.currency}.</p>}

    <dl className="credit-breakdown"><div><dt>Welcome credit</dt><dd>{credit(data.welcomeMinor)}</dd></div><div><dt>Referral credits</dt><dd>{credit(data.referralMinor)}</dd></div><div><dt>Rewarded friends</dt><dd>{data.referralSlots} / {data.founderOrdinal?3:0}</dd></div></dl></>}
    <section className="account-section"><p className="eyebrow">YOUR NAME IS THE ADDRESS</p><h2>Put your bank behind @{data.handle}.</h2><p className="small-copy">Add your receiving account once. Friends can use your username instead of asking for your IBAN. Account ownership is not yet bank-verified.</p><Link className="button primary" href="/account/receiving">Set up receiving account<ArrowUpRight size={17}/></Link><Link className="button secondary" href="/pay">Pay by username<ArrowUpRight size={17}/></Link></section>
    <button className="button primary" onClick={share}><Share2 size={17}/>Invite a friend</button>
    {data.eligibility==='review_required'&&<p className="notice">Your account is under review. Your reserved handle is available.</p>}
    {data.eligibility==='excluded'&&<p className="notice">Your handle is reserved. This account is classified separately from independent waitlist participants.</p>}
    <div className="invite-actions"><button className="button secondary" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy invite'}</button><button className="button secondary" onClick={()=>setShowQr(true)}><QrCode size={18}/>Show invite QR</button></div>
    {hasCredits&&<p className="small-copy credit-disclosure">Promotional launch fee credits—not cash. Reserved for eligible NEYLO service fees when available. The welcome and referral promotion has ended. Credits already earned remain reserved. <Link href="/terms">Terms <ArrowUpRight size={13}/></Link></p>}
    {data.referrals.length>0&&<section className="account-section"><h2>Your invitations</h2><ul className="activity-list">{data.referrals.map((r,index)=><li key={r.id}><span>Invitation {data.referrals.length-index}</span><span className={`referral-state state-${r.status}`}>{r.reason==='promotion_ended'?'Joined the waitlist':r.status==='credited'?`Credited · +${credit(5000)}`:r.status==='review_required'?'Review required':r.status==='qualified'?'Qualified · cap reached':r.status==='ineligible'?'Ineligible':'Pending'}</span></li>)}</ul></section>}
    {hasCredits&&<section className="account-section"><h2>Credit history</h2>{data.entries.length?<ul className="activity-list">{data.entries.map(entry=><li key={entry.id}><span>{entry.type==='welcome'?'Welcome entitlement':entry.type==='referral'?'Referral entitlement':'Credit reversal'}<small>{new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeZone:'Europe/Sarajevo'}).format(new Date(entry.createdAt))}</small></span><strong>{entry.amountMinor>0?'+':''}{credit(entry.amountMinor)}</strong></li>)}</ul>:<p className="small-copy">No promotional credit has been granted to this account.</p>}</section>}
    <section className="account-section pilot"><p className="eyebrow">OPTIONAL · AFTER YOU’RE IN</p><h2>Help shape what comes next.</h2><p>Interested in trying NEYLO when a pilot is available?</p><button className="button secondary" disabled={busy} onClick={()=>pilot(!data.pilotInterest)}>{data.pilotInterest?<><Check size={16}/>Interested · click to undo</>:'I’m interested in a pilot'}</button><p className="small-copy">Entirely optional. Your place on the waitlist stays the same.</p></section>
    <details className="settings"><summary>Account & privacy settings</summary><p className="verified-contact">Verified email <strong>{data.email}</strong></p><label className="checkbox-row"><input type="checkbox" checked={data.analyticsConsent} disabled={busy} onChange={e=>changePreference(e.target.checked,data.marketingConsent)}/><span>Allow optional product analytics</span></label><label className="checkbox-row"><input type="checkbox" checked={data.marketingConsent} disabled={busy} onChange={e=>changePreference(data.analyticsConsent,e.target.checked)}/><span>Receive optional marketing updates</span></label>{data.acceptedAt?<p className="small-copy">Accepted <Link href={`/terms?version=${encodeURIComponent(data.termsVersion)}`}>{data.termsVersion}</Link> on {new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeZone:'Europe/Sarajevo'}).format(new Date(data.acceptedAt))}.</p>:<p className="small-copy">Campaign acceptance was not included with your account import. Contact support to complete the consent and eligibility review. <Link href="/terms">Read campaign terms</Link>.</p>}{support?<a href={`mailto:${support}`}>Contact support</a>:<Link href="/support">Support information</Link>}<div className="settings-actions"><button className="text-button danger" disabled={busy||Boolean(data.deletionStatus)} onClick={deleteRequest}>{data.deletionStatus?`Deletion request: ${data.deletionStatus.replaceAll('_',' ')}`:'Request account deletion'}</button><button className="text-button" disabled={busy} onClick={logout}><LogOut size={15}/>Sign out</button></div></details>
    <p className="refresh-note">{isValidating?'Refreshing your account…':'Updates automatically while this page is visible.'}</p></div>
    {showQr&&<QrSheet url={invitation} handle={data.handle} onClose={()=>setShowQr(false)}/>}
  </main>;
}
