export const CHAPTERS=[
  {id:'vision',label:'The idea',seconds:14,note:'Sending money starts with a person. Yet the experience still asks us to think in account numbers, networks and payment rails. NEYLO is one address for money: a familiar name on the surface, with a routing engine underneath.'},
  {id:'problem',label:'The friction',seconds:16,note:'You know who you want to pay. Why should you have to know how their money infrastructure works? Fees, currency conversion and delivery speed are separate decisions today. Our thesis is that the software should resolve that complexity around the person.'},
  {id:'solution',label:'The product',seconds:18,note:'The product has three layers. A personal address identifies the recipient. A routing policy compares eligible paths. A single journey preserves the amount, fee and progress. The address stays simple as the underlying financial infrastructure becomes more capable.'},
  {id:'engine',label:'The engine',seconds:22,note:'This route selection is real application logic. Change the amount and the fees and recipient amount recalculate in integer minor units. Choose fastest and the engine ranks the eligible routes by time. The rates and providers here are configured fixtures; they are not live provider quotes.'},
  {id:'experience',label:'The experience',seconds:20,note:'Here is the part you can touch. Open Nadin and pair Kerim on another screen. A send creates one durable shared transfer, and both pages resolve into the same receipt. Financial execution is simulated for this hackathon. The synchronization, persistence and routing behavior are working software.'},
  {id:'traction',label:'The signal',seconds:24,note:'These numbers come from our production account database, refreshed during this presentation. Read the current total on screen. We separately show signups verified through NEYLO and owner-attested imports. Staff, tests and incomplete attempts are excluded. This is an early registration signal, not active usage or payment volume.'},
  {id:'market',label:'The first market',seconds:16,note:'Our proposed starting point is people moving money between Bosnia and the euro area, especially repeat family and freelance payments. The broader remittance market is large, but our first test is deliberately narrow: can one corridor deliver a better repeat experience?'},
  {id:'business',label:'The business',seconds:18,note:'The business hypothesis is a transparent service fee on completed payments, with business payout tooling as an expansion path. This model shows the arithmetic, not achieved revenue. Provider, foreign-exchange, compliance and loss costs must be validated before we claim attractive margins.'},
  {id:'execution',label:'The path',seconds:18,note:'The acquisition system, handle reservations, referral accounting and connected experience are built. Production payment execution still needs provider integration and a reviewed operating model. The next milestone is one instrumented pilot corridor, followed by evidence of repeat use and sustainable unit economics.'},
  {id:'next',label:'The invitation',seconds:14,note:'We are building the layer that lets money start with a name. Our next ask is a pilot partner, a focused first cohort, and help navigating the operating requirements. Try the connected experience, reserve an address, and help us prove the first corridor.'},
] as const;

export const SOURCES={
  prices:{url:'https://remittanceprices.worldbank.org/sites/default/files/2026-04/RPW_main_report_and_annex_Q325.pdf',label:'World Bank · Remittance Prices Worldwide, Q3 2025'},
  flows:{url:'https://blogs.worldbank.org/en/peoplemove/in-2024--remittance-flows-to-low--and-middle-income-countries-ar',label:'World Bank · December 2024 estimate'},
};
