export const CHAPTERS = [
  { id: 'vision', label: 'One address', seconds: 12, note: 'You know the person. Your payment app should know the way. NEYLO gives people and businesses one human-readable address to receive, request and route money. A simple identity above increasingly capable financial infrastructure.' },
  { id: 'problem', label: 'The pain', seconds: 18, note: 'Imagine paying a friend back. First you ask which bank. Then you copy their account number. Across a border, you also choose a currency, compare fees and wonder what will arrive. The human intent is simple. The experience makes the sender assemble the payment.' },
  { id: 'timing', label: 'Why now', seconds: 22, note: 'Bosnia and Herzegovina is making its largest payment-system modernization in 25 years. IPS BiH launched on 20 July 2026. A financial-law package was adopted in July, alongside PSD2-aligned payment-services reform. The country applied to SEPA on 6 August. Application is not membership. New infrastructure creates an opening for a better consumer layer; it does not give NEYLO automatic bank access.' },
  { id: 'solution', label: 'The product', seconds: 16, note: 'With NEYLO, start with an address, not an account number. Choose the person, see the recipient amount and fee, then follow one continuous journey. Our vision is a portable address across institutions. Today we have persistent identities and a working routing experience; provider connectivity is the next gate.' },
  { id: 'engine', label: 'The engine', seconds: 14, note: 'The engine calculates eligible paths in integer minor units. Change the amount or select fastest and the fee and recipient amount actually recalculate. These are configured fee, FX and timing assumptions, not live provider quotes. The interface and the routing logic use the same functions.' },
  { id: 'experience', label: 'Try it', seconds: 24, note: 'Financial execution is simulated for this hackathon. The software synchronization is real: open neylo.xyz/demo/nadin and neylo.xyz/demo/kerim on two devices. They join the same presentation session automatically. Tap Kerim, enter an amount and send. A durable shared event resolves on both screens after about 15 seconds. That is presentation playback, not a measured bank-settlement time.' },
  { id: 'traction', label: 'The signal', seconds: 16, note: 'Read the current registration count on screen. It comes from our production database and refreshes every 30 seconds. NEYLO email-code signups and operator-attested imports are shown separately. Test, staff and incomplete records are excluded. This is early interest, not active payment usage or revenue.' },
  { id: 'market', label: 'The wedge', seconds: 10, note: 'Start with everyday payments in Bosnia, then a focused Bosnia–euro area corridor for families and freelancers. Win a repeat use case, measure recipient activation, and earn the right to expand.' },
  { id: 'business', label: 'The model', seconds: 14, note: 'A transparent service fee is our business hypothesis. Business collections and payouts can follow. This interactive model shows arithmetic, not achieved revenue. Actual provider, FX, compliance and support costs must establish whether the economics work.' },
  { id: 'roadmap', label: '1 · 5 · 10 years', seconds: 20, note: 'In year one, prove one authorized provider corridor with reconciliation, support and repeat use. In five years, aim for regional reach and business payment tools, expanding only where integrations and unit economics work. In ten years, our ambition is a portable payment identity across institutions and apps. These are staged ambitions, not promised coverage.' },
  { id: 'next', label: 'The ask', seconds: 14, note: 'The rails are becoming faster. Let us make the experience human. We are looking for one pilot integration partner, a focused first cohort, and operating expertise. Try the two-screen experience and join the waitlist. One address for money. Built in Sarajevo.' },
] as const;

export const SOURCES = {
  ips: { url: 'https://www.cbbh.ba/press/ShowNews/1798', label: 'CBBH · IPS BiH launch, 20 July 2026' },
  reform: { url: 'https://www.cbbh.ba/press/ShowNews/1804', label: 'CBBH · Financial-law package adopted, 28 July 2026' },
  psd2: { url: 'https://parlamentfbih.gov.ba/v2/userfiles/file/Materijali%20u%20proceduri_2026/293-26-P_Z_%20O%20PLATNIM%20USLUGAMA-B.pdf', label: 'Parliament of FBiH · Payment-services reform and PSD2 alignment' },
  sepa: { url: 'https://www.cbbh.ba/press/ShowNews/1808?lang=en', label: 'CBBH · SEPA application, 6 August 2026' },
};
