export const CHAPTERS = [
  { id: 'vision', label: 'One address', seconds: 13,
    cue: 'Look at the audience. Pause after “right now” and after the final question. Do not wait for an answer.',
    note: 'Think of someone you could message right now. You know their name. You probably don’t know their bank account number. Why should paying them require it?' },
  { id: 'problem', label: 'The pain', seconds: 15,
    cue: 'Deliver the four questions as a familiar conversation. Keep the tone warm, not frustrated.',
    note: 'You want to pay a friend back. Suddenly it’s: “Which bank?” “Send your account number.” “What’s the fee?” “Has it arrived?” A simple favor becomes a conversation about banking.' },
  { id: 'timing', label: 'Why now', seconds: 24,
    cue: 'Indicate the three milestones. Keep exact dates and source links on screen; SEPA application does not mean membership or NEYLO bank access.',
    note: 'Bosnia and Herzegovina is making its biggest payment-system upgrade in 25 years. IPS BiH launched in July. Financial reforms were adopted, with PSD2 alignment shaping payment services. In August, the country applied to SEPA. The infrastructure is changing. This is our opening to build a simpler experience on top.' },
  { id: 'solution', label: 'The product', seconds: 17,
    cue: 'Say “at Kerim” and point to the address. Slow down for “choose who”.',
    note: 'NEYLO gives that experience a name: @kerim. Choose who, see the fee and what arrives, then follow the journey. We’re building one address for people and businesses to receive, request and route money.' },
  { id: 'engine', label: 'The engine', seconds: 13,
    cue: 'Select Fastest once in the workbench. If the control pauses guided playback, continue manually with the chapter controls.',
    note: 'Choose lowest cost or fastest. Change the amount. Our engine recalculates the fee and what arrives, using configured cost and exchange-rate assumptions. Every screen follows the same calculation.' },
  { id: 'experience', label: 'Try it', seconds: 28,
    cue: 'Have Nadin’s 25 KM composer ready and Kerim connected. Say the disclosure before clicking Send. Click just after “Watch Nadin send”. Show the arrival, then say the last sentence only when its matching receipt is visible. The 15 seconds are playback, not bank settlement.',
    note: 'Financial execution is simulated for this hackathon. Our bank integrations come next. Watch Nadin send 25 KM to @kerim. Both devices follow the same transfer. This fifteen-second playback ends with one matching receipt: 24.90 KM for Kerim.' },
  { id: 'traction', label: 'The signal', seconds: 16,
    cue: 'Point to the current count and its two verification categories. Do not memorize a count or call registrations active users. If the endpoint is unavailable, say the count is unavailable.',
    note: 'That registration count comes from our actual database. It separates NEYLO-verified signups from owner-attested imports and excludes staff and tests. It measures early interest. Our next proof is whether people return to send again.' },
  { id: 'market', label: 'The wedge', seconds: 11,
    cue: 'Name the first audience clearly: families and freelancers. Avoid adding more markets.',
    note: 'We start with everyday payments in Bosnia, then a focused Bosnia–euro area corridor for families and freelancers. One useful habit gives us a reason to expand.' },
  { id: 'business', label: 'The model', seconds: 11,
    cue: 'Leave the calculator still. This is the proposed business model, not existing revenue.',
    note: 'Our model is a transparent fee on completed payments, with business collections and payouts later. The pilot must prove customer value and economics after operating costs.' },
  { id: 'roadmap', label: '1 · 5 · 10 years', seconds: 20,
    cue: 'Select each horizon as you say it. These are ambitions gated by authorized integrations and viable operations.',
    note: 'Year one: connect an authorized provider and prove a repeatable payment journey. Year five: expand regionally, with payment tools for businesses. Year ten: make your payment address portable across institutions and apps. Each step earns the next through working integrations and repeat use.' },
  { id: 'next', label: 'The ask', seconds: 12,
    cue: 'Return your attention to the audience. Pause before “NEYLO”. Finish on the last line without adding a second closing.',
    note: 'We’re looking for a pilot integration partner and our first payment cohort. Help us make paying someone as natural as messaging them. NEYLO. You know who. We find the way.' },
] as const;

export const SOURCES = {
  ips: { url: 'https://www.cbbh.ba/press/ShowNews/1798', label: 'CBBH · IPS BiH launch, 20 July 2026' },
  reform: { url: 'https://www.cbbh.ba/press/ShowNews/1804', label: 'CBBH · Financial-law package adopted, 28 July 2026' },
  psd2: { url: 'https://parlamentfbih.gov.ba/v2/userfiles/file/Materijali%20u%20proceduri_2026/293-26-P_Z_%20O%20PLATNIM%20USLUGAMA-B.pdf', label: 'Parliament of FBiH · Payment-services reform and PSD2 alignment' },
  sepa: { url: 'https://www.cbbh.ba/press/ShowNews/1808?lang=en', label: 'CBBH · SEPA application, 6 August 2026' },
};
