'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { MotionConfig,motion,useReducedMotion } from 'motion/react';
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight,Clock3,Download,Expand,Layers3,Monitor,Pause,Play,Shrink,Sparkles,StickyNote,X } from 'lucide-react';
import { AddressCore,AddressLayers,ConnectedPreview,RoutingProof } from './visuals';
import { LiveBadge,LiveTraction,usePitchMetrics } from './live-traction';
import { CHAPTERS } from './content';
import { FrictionStory,ModernizationTimeline,Roadmap } from './story';
import { opportunityModel } from './metrics';
import './pitch.css';

export function Pitch(){
  const live=usePitchMetrics(),systemReduced=useReducedMotion();
  const [projector,setProjector]=useState(true);
  const [active,setActive]=useState(0),[guided,setGuided]=useState(false),[notes,setNotes]=useState(false),[reduce,setReduce]=useState(false),[fullscreen,setFullscreen]=useState(false),[hidden,setHidden]=useState(false),[announcement,setAnnouncement]=useState('');
  const root=useRef<HTMLElement>(null),reduced=Boolean(systemReduced||reduce);
  function go(index:number){const chapter=CHAPTERS[Math.max(0,Math.min(CHAPTERS.length-1,index))];if(!chapter)return;document.getElementById(chapter.id)?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}
  useEffect(()=>{
    const ratios=new Map<string,number>();
    const observer=new IntersectionObserver(entries=>{for(const entry of entries)ratios.set(entry.target.id,entry.intersectionRatio);let best=0,index=0;for(let i=0;i<CHAPTERS.length;i++){const ratio=ratios.get(CHAPTERS[i]?.id??'')??0;if(ratio>best){best=ratio;index=i;}}if(best>0)setActive(index);},{rootMargin:'-72px 0px -10% 0px',threshold:[0,.1,.25,.5,.75,1]});
    for(const chapter of CHAPTERS){const element=document.getElementById(chapter.id);if(element)observer.observe(element);}return()=>observer.disconnect();
  },[]);
  useEffect(()=>{if(!guided||hidden)return;const chapter=CHAPTERS[active];if(!chapter)return;
    const element=document.getElementById(chapter.id);
    const pan=element&&element.getBoundingClientRect().height>innerHeight+20?setTimeout(()=>element.scrollIntoView({behavior:reduced?'instant':'smooth',block:'end'}),chapter.seconds*550):undefined;
    const timer=setTimeout(()=>{if(active===CHAPTERS.length-1)setGuided(false);else go(active+1);},chapter.seconds*1000);
    return()=>{clearTimeout(timer);if(pan)clearTimeout(pan);};
  },[guided,active,hidden,reduced]);
  useEffect(()=>{
    function key(event:KeyboardEvent){if(event.altKey||event.ctrlKey||event.metaKey||event.target instanceof Element&&event.target.closest('input,textarea,select,dialog,[role=tablist]'))return;
      const direction=event.key==='ArrowRight'||event.key==='PageDown'?1:event.key==='ArrowLeft'||event.key==='PageUp'?-1:0;
      if(direction){event.preventDefault();setGuided(false);go(active+direction);}if(event.key==='Escape'){setGuided(false);setNotes(false);}}
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  },[active,reduced]);
  useEffect(()=>{const visibility=()=>{setHidden(document.hidden);if(document.hidden)setGuided(false);};const full=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',full);return()=>{document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',full);};},[]);
  async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.current?.requestFullscreen)await root.current.requestFullscreen();else setAnnouncement('Fullscreen is unavailable in this browser. The pitch remains usable.');}catch{setAnnouncement('Fullscreen was unavailable. Use the arrow controls to continue.');}}

  return <MotionConfig reducedMotion={reduced?'always':'user'} transition={{duration:.45,ease:[.22,1,.36,1]}}><main ref={root} id="main" className="neylo-pitch" data-pitch data-theme={projector?'projector':'sapphire'} data-reduced={reduced} data-quiet={hidden} data-chapter={CHAPTERS[active]?.id} onPointerDownCapture={e=>{if(!(e.target instanceof Element&&e.target.closest('[data-playback]')))setGuided(false);}} onKeyDownCapture={e=>{if(e.target instanceof Element&&e.target.closest('input,select,[role=tab],button,a')&&!e.target.closest('[data-playback]'))setGuided(false);}} onWheel={()=>setGuided(false)} onTouchStart={e=>{if(!(e.target instanceof Element&&e.target.closest('[data-playback]')))setGuided(false);}}>
    <header className="pitch-header"><Link className="pitch-logo" href="/">neylo<span>↗</span></Link><span className="pitch-header-caption">ONE ADDRESS FOR MONEY</span><div className="pitch-header-actions"><button className="pitch-theme-toggle" aria-pressed={projector} aria-label="Projector palette" onClick={()=>setProjector(value=>!value)}><Monitor size={17}/><span>{projector?'Projector':'Sapphire'}</span></button><button className="pitch-text-action" aria-label="Speaker notes" onClick={()=>{setNotes(true);setGuided(false);}}><StickyNote size={16}/><span>Speaker notes</span></button><button className="pitch-icon-button" aria-label={fullscreen?'Exit fullscreen':'Enter fullscreen'} onClick={()=>void toggleFullscreen()}>{fullscreen?<Shrink size={18}/>:<Expand size={18}/>}</button></div></header>
    <nav className="pitch-chapter-rail" aria-label="Pitch chapters">{CHAPTERS.map((chapter,i)=><a key={chapter.id} href={`#${chapter.id}`} aria-label={`${i+1}. ${chapter.label}`} aria-current={active===i?'step':undefined} onClick={e=>{e.preventDefault();setGuided(false);go(i);}}><span>{String(i+1).padStart(2,'0')}</span><i/><b>{chapter.label}</b></a>)}</nav>

    <section id="vision" className="pitch-chapter pitch-hero" aria-labelledby="vision-title"><div className="pitch-wrap pitch-hero-grid"><div className="pitch-hero-copy"><div className="pitch-eyebrow"><span className="pitch-tiny-dot"/>BUILT IN SARAJEVO / 2026</div><h1 id="vision-title">You know <em>who.</em><br/>We find <em>the way.</em></h1><p className="pitch-lead">One <strong>@address</strong> for money.<br/>Across the institutions underneath.</p><div className="pitch-hero-actions"><button className="pitch-button" onClick={()=>go(1)}>Meet NEYLO <ArrowRight size={18}/></button><button className="pitch-play-link" data-playback onClick={()=>{go(0);setGuided(true);}}><Play size={15}/>Play the 3-minute pitch</button></div><LiveBadge live={live}/></div><AddressCore reduced={reduced}/></div><div className="pitch-hero-bottom pitch-wrap"><span>THE HUMAN LAYER FOR A NEW PAYMENT ERA.</span><button onClick={()=>go(1)} aria-label="Continue to the problem"><ArrowDown size={18}/></button><span>SCROLL TO EXPLORE / → TO PRESENT</span></div></section>

    <Chapter id="problem" eyebrow="01 / THE EVERYDAY FRICTION" title={<>Paying a person.<br/><em>Solving a process.</em></>} intro="The intent takes a second. The details get in the way."><FrictionStory/></Chapter>

    <Chapter id="timing" eyebrow="02 / WHY NOW · BOSNIA & HERZEGOVINA" title={<>New rails.<br/><em>A rare opening.</em></>} intro="The country’s largest payment-system modernization in 25 years. The experience can finally catch up."><ModernizationTimeline/></Chapter>

    <Chapter id="solution" eyebrow="03 / THE HUMAN LAYER" title={<>A name above<br/><em>the account number.</em></>} intro="Receive. Request. Route. One recognizable identity across the financial institutions you use."><div className="pitch-solution-grid"><div className="pitch-solution-statement"><span className="pitch-statement-address">@yourname</span><h3>Keep the person.<br/>Resolve the complexity.</h3><p>Choose who. See what arrives. Follow one continuous journey.</p><span className="pitch-concept-label"><Layers3 size={18}/>Explore the three layers</span></div><AddressLayers/></div></Chapter>

    <Chapter id="engine" eyebrow="04 / WORKING ROUTING LOGIC" title={<>Your priority.<br/><em>A calculated route.</em></>} intro="Change 100 to 200. Choose Fastest. The engine recalculates the actual trade-off."><div className="pitch-engine-grid"><div className="pitch-engine-copy"><h3>Simple above.<br/>Deliberate underneath.</h3><ol><li><span>01</span><div><strong>Check eligibility</strong><p>Source, destination, currency, amount.</p></div></li><li><span>02</span><div><strong>Calculate the outcome</strong><p>Fee, recipient amount, delivery estimate.</p></div></li><li><span>03</span><div><strong>Rank for your priority</strong><p>Lowest cost or fastest eligible path.</p></div></li></ol></div><RoutingProof/></div></Chapter>

    <Chapter id="experience" eyebrow="05 / PUT IT IN YOUR HANDS" title={<>One person sends.<br/><em>Another sees it arrive.</em></>} intro="Two devices. The same transfer, progress and receipt. Open both pages and try it."><ConnectedPreview/><div className="pitch-demo-launch"><div><Link className="pitch-button" href="/demo/nadin" target="_blank" rel="noopener noreferrer">Open Nadin <ArrowUpRight size={18}/></Link><Link className="pitch-button pitch-button-secondary" href="/demo/kerim" target="_blank" rel="noopener noreferrer">Open Kerim <ArrowUpRight size={18}/></Link><Link className="pitch-text-action" href="/app/demo" target="_blank" rel="noopener noreferrer">Routing app <ArrowUpRight size={16}/></Link></div><p>Both URLs connect automatically. Shared software state is real; external financial execution is simulated for the hackathon.</p></div></Chapter>

    <Chapter id="traction" eyebrow="06 / EARLY INTEREST, MEASURED" title={<>People are claiming<br/><em>their place.</em></>} intro="The waitlist is open. These are actual registration records, refreshed during this presentation."><LiveTraction live={live}/></Chapter>

    <Chapter id="market" eyebrow="07 / A FOCUSED FIRST MARKET" title={<>Start close.<br/><em>Earn the next corridor.</em></>} intro="Everyday local payments first. A Bosnia–euro area pilot next, for families and freelancers."><div className="pitch-wedge"><div><span>01 / LOCAL UTILITY</span><h3>Pay a person back.</h3><p>One address across participating institutions. Prove a useful everyday habit.</p></div><div><span>02 / REPEAT NEED</span><h3>Bridge home and abroad.</h3><p>Family support and freelance income, with the recipient amount clear upfront.</p></div><div><span>03 / BUSINESS UTILITY</span><h3>Make the next payout easier.</h3><p>Expand into requests, collections and batches after the first route works.</p></div></div><div className="pitch-market-gate"><strong>First proof:</strong> a connected provider path, repeat use and actual unit economics.</div></Chapter>

    <Chapter id="business" eyebrow="08 / THE BUSINESS HYPOTHESIS" title={<>Earn trust.<br/><em>Earn a transparent fee.</em></>} intro="A service fee on completed payments. Business tools as a later expansion. Explore the arithmetic."><BusinessModel/></Chapter>

    <Chapter id="roadmap" eyebrow="09 / THE NEXT 1 · 5 · 10 YEARS" title={<>A narrow first proof.<br/><em>A much larger ambition.</em></>} intro="Built today: persistent identities, calculated routing and synchronized journeys. Next: connect financial execution."><Roadmap/></Chapter>

    <section id="next" className="pitch-chapter pitch-finale" aria-labelledby="next-title"><div className="pitch-wrap"><div className="pitch-eyebrow">10 / THE INVITATION</div><div className="pitch-finale-mark" aria-hidden="true">@</div><h2 id="next-title">Let money<br/>start with <em>a name.</em></h2><p className="pitch-lead">Help us prove the first corridor.</p><div className="pitch-ask-list"><span>01 · Pilot partner</span><span>02 · First cohort</span><span>03 · Operating expertise</span></div><div className="pitch-finale-actions"><Link className="pitch-button" href="/">Join the waitlist <ArrowUpRight size={18}/></Link><Link className="pitch-text-action" href="/demo/nadin" target="_blank" rel="noopener noreferrer">Try the connected product <ArrowUpRight size={16}/></Link></div><div className="pitch-founder"><strong>Kerim Sabić</strong><span>Horalix d.o.o. · Sarajevo</span><a href="mailto:kerim@horalix.com">kerim@horalix.com <ArrowUpRight size={14}/></a></div><div className="pitch-finale-footer"><span className="pitch-logo">neylo<span>↗</span></span><span>ONE ADDRESS FOR MONEY.</span><a href="#vision" onClick={e=>{e.preventDefault();go(0);}}>Back to the beginning ↑</a></div></div></section>

    <div className="pitch-player"><div className="pitch-player-index"><b>{String(active+1).padStart(2,'0')}</b><span>/ {String(CHAPTERS.length).padStart(2,'0')}</span><span>{CHAPTERS[active]?.label}</span></div><div className="pitch-player-progress" aria-hidden="true"><i style={{width:`${(active+1)/CHAPTERS.length*100}%`}}/></div><div className="pitch-player-controls"><button className="pitch-icon-button" aria-label="Previous chapter" disabled={active===0} onClick={()=>go(active-1)}><ArrowLeft size={18}/></button><button className="pitch-icon-button" data-playback aria-label={guided?'Pause guided pitch':'Play guided pitch'} onClick={()=>{if(!guided&&active===CHAPTERS.length-1)go(0);setGuided(!guided);}}>{guided?<Pause size={17}/>:<Play size={17}/>}</button><button className="pitch-icon-button" aria-label="Next chapter" disabled={active===CHAPTERS.length-1} onClick={()=>go(active+1)}><ArrowRight size={18}/></button><button className={`pitch-motion-control ${reduced?'is-reduced':''}`} aria-pressed={reduced} aria-label="Reduce motion" onClick={()=>setReduce(!reduce)}><Sparkles size={16}/></button></div></div>
    <div className="pitch-sr-only" role="status">{announcement}{guided?'Guided pitch playing. Any manual interaction pauses it.':''}</div>
    <SpeakerNotes open={notes} onClose={()=>setNotes(false)} active={active}/>
  </main></MotionConfig>;
}

function Chapter({id,eyebrow,title,intro,children}:{id:string;eyebrow:string;title:React.ReactNode;intro:string;children:React.ReactNode}){
  return <section id={id} className="pitch-chapter" aria-labelledby={`${id}-title`}><div className="pitch-wrap"><motion.div className="pitch-section-heading" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.6,ease:[.22,1,.36,1]}}><div className="pitch-eyebrow">{eyebrow}</div><h2 id={`${id}-title`}>{title}</h2><p className="pitch-intro">{intro}</p></motion.div>{children}</div></section>;
}

function BusinessModel(){
  const [senders,setSenders]=useState(1000),[fee,setFee]=useState(50);
  const result=opportunityModel(senders,2,150,fee);
  const eur=(minor:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(minor/100);
  return <div className="pitch-business-model"><div className="pitch-model-assumptions"><div className="pitch-eyebrow">EXPLORE THE ASSUMPTIONS</div><label htmlFor="pitch-senders">Monthly transacting senders <strong>{senders.toLocaleString('en-GB')}</strong></label><input id="pitch-senders" type="range" min="1000" max="10000" step="1000" value={senders} onChange={e=>setSenders(Number(e.target.value))}/><div className="pitch-range-ends"><span>1,000</span><span>10,000</span></div><label htmlFor="pitch-fee">Illustrative service fee <strong>{(fee/100).toFixed(2)}%</strong></label><input id="pitch-fee" type="range" min="25" max="100" step="25" value={fee} onChange={e=>setFee(Number(e.target.value))}/><div className="pitch-range-ends"><span>0.25%</span><span>1.00%</span></div><dl><div><dt>Transfers per sender / month</dt><dd>2</dd></div><div><dt>Average transfer</dt><dd>€150</dd></div></dl></div><div className="pitch-model-output" aria-live="polite"><span>MONTHLY SCENARIO</span><div><small>Payment volume</small><strong>{eur(result.volumeMinor)}</strong></div><div><small>Gross service-fee revenue</small><strong className="pitch-model-revenue">{eur(result.revenueMinor)}</strong></div><p>Model assumptions, not achieved revenue. Before provider, FX, compliance, support and loss costs. Pricing and margins require validation.</p></div></div>;
}

function SpeakerNotes({open,onClose,active}:{open:boolean;onClose:()=>void;active:number}){
  const ref=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null);
  useEffect(()=>{const dialog=ref.current;if(!dialog)return;if(open){opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;dialog.showModal();}else if(dialog.open){dialog.close();opener.current?.focus();}},[open]);
  return <dialog ref={ref} className="pitch-notes" aria-labelledby="pitch-notes-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="pitch-notes-inner"><header><div><span className="pitch-eyebrow">PRESENTER / 3 MINUTES</span><h2 id="pitch-notes-title">The story behind the screen.</h2></div><button className="pitch-icon-button" aria-label="Close speaker notes" onClick={onClose}><X size={22}/></button></header><div className="pitch-notes-current"><span>NOW / {CHAPTERS[active]?.label}</span><p>{CHAPTERS[active]?.note}</p></div><a className="pitch-text-action" href="/pitch/script" download><Download size={16}/>Download the full script</a><details><summary>Read the complete pitch</summary>{CHAPTERS.map((chapter,i)=><section key={chapter.id}><h3>{String(i+1).padStart(2,'0')} / {chapter.label} <small>{chapter.seconds}s</small></h3><p>{chapter.note}</p></section>)}</details><p className="pitch-notes-tip"><Clock3 size={16}/>Arrow keys move between chapters. Manual interaction pauses guided playback.</p></div></dialog>;
}
