'use client';
import { useState } from 'react';
import Link from 'next/link';
import useSWR from 'swr';
import { Download,RefreshCw,ArrowUpRight } from 'lucide-react';
import { metricsSchema,formatCredit,type Metrics } from '@/lib/domain';
import { request } from '@/lib/client';

export function Dashboard({initial,role,judge=false}:{initial:Metrics;role:'operator'|'presenter';judge?:boolean}){
  const [cohort,setCohort]=useState('participants'),[from,setFrom]=useState('2026-01-01'),[to,setTo]=useState('');
  const query=new URLSearchParams({cohort,from:`${from||'2026-01-01'}T00:00:00.000Z`,to:to?`${to}T23:59:59.999Z`:'2100-01-01T00:00:00.000Z'}).toString();
  const {data,error,mutate,isValidating}=useSWR(`admin/metrics?${query}`,path=>request(path,metricsSchema),{fallbackData:initial,keepPreviousData:false,refreshInterval:30000,revalidateOnFocus:true,refreshWhenHidden:false});
  const stats=data??initial;
  const selectionMatches=stats.cohort===cohort&&Date.parse(stats.from)===Date.parse(`${from||'2026-01-01'}T00:00:00.000Z`)&&Date.parse(stats.to)===Date.parse(to?`${to}T23:59:59.999Z`:'2100-01-01T00:00:00.000Z');
  const cards=[['Finalized handles',stats.finalizedHandles,'One reserved handle per account'],['Founding accounts',stats.foundingAccounts,'Accounts allocated a welcome entitlement'],['Qualified referrals',stats.qualifiedReferrals,'Eligible completed referred accounts'],['Credited referrals',stats.creditedReferrals,'Referral awards, before any reversals'],['Pending attempts',stats.pendingAttempts,`${stats.activeHolds} holds still active`],['Pilot interest',stats.pilotInterest,'Optional, recorded after completion']];
  return <main id="main" className={`dashboard ${judge?'judge-mode':''}`}><div className="dashboard-heading"><div><p className="eyebrow">{judge?'JUDGE MODE · AGGREGATES ONLY':'NEYLO · VALIDATION'}</p><h1>Real accounts.<br/>A clear beginning.</h1></div><div className="dashboard-actions">{!judge&&role==='operator'&&<Link className="button secondary" href="/admin/accounts">Registered accounts<ArrowUpRight size={15}/></Link>}<Link className="button secondary" href={judge?'/admin/validation':'/judge'}>{judge?'Validation dashboard':'Open Judge Mode'}<ArrowUpRight size={15}/></Link><a className="button secondary" href={`/api/admin/export?${query}`}><Download size={15}/>Export CSV</a></div></div>
    <div className="dashboard-filters"><label>Cohort<select value={cohort} onChange={e=>setCohort(e.target.value)}><option value="participants">Participants · staff/tests excluded</option><option value="independent">Independent participants</option><option value="founder_assisted">Founder-assisted participants</option><option value="staff">Staff</option><option value="test">Test accounts</option><option value="compensated">Compensated research</option><option value="all">All accounts · includes staff/tests</option></select></label><label>From (UTC)<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through (UTC)<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="icon-button" aria-label="Refresh metrics" onClick={()=>mutate()}><RefreshCw size={19} className={isValidating?'refreshing':''}/></button></div>
    <p className={`dashboard-freshness ${error?'form-error':''}`} role="status">{!selectionMatches?(error?'Could not load this selection. Check the date range and retry.':'Loading the selected accounts…'):error?'Refresh failed. These figures may be stale.':isValidating?'Refreshing…':`Last refreshed ${new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'medium',timeZone:'Europe/Sarajevo'}).format(new Date(stats.asOf))} · Europe/Sarajevo`}</p>
    {selectionMatches&&<>
    <section className="headline-metric"><div><p>Verified completed accounts</p><strong>{stats.verifiedCompleted}</strong><span>Distinct completed NEYLO accounts linked to verified Auth identities.</span></div><div className="headline-context"><p><strong>{stats.remainingFounders}</strong> / 100 founding places remaining</p><p><span className="status-dot"/>{stats.paused?'New enrollment paused':'Enrollment open'}</p><p>{stats.lifetimeVerified} lifetime accounts across all cohorts.</p></div></section>
    <section className="metric-grid" aria-label="Signup and referral metrics">{cards.map(([label,value,definition])=><article key={String(label)}><p>{label}</p><strong>{value}</strong><span>{definition}</span></article>)}</section>
    <section className="entitlement-summary"><div><p>Reserved promotional credits</p><strong>{formatCredit(stats.reservedMinor)}</strong><span>Launch fee entitlements. Not revenue, deposits, or money transferred.</span></div><dl><div><dt>Granted</dt><dd>{formatCredit(stats.grantedMinor)}</dd></div><div><dt>Reversed</dt><dd>{formatCredit(stats.reversedMinor)}</dd></div><div><dt>Configured campaign ceiling</dt><dd>{formatCredit(stats.configuredCeilingMinor)}</dd></div></dl></section>
    <div className="dashboard-columns"><section><h2>Campaign source</h2><table><thead><tr><th>Source</th><th>Completed accounts</th></tr></thead><tbody>{stats.sources.length?stats.sources.map(row=><tr key={row.source}><td>{row.source}</td><td>{row.accounts}</td></tr>):<tr><td colSpan={2}>No completed accounts in this selection.</td></tr>}</tbody></table></section><section><h2>Participant classification</h2><p className="small-copy">All cohorts in the selected date range, shown separately for context.</p><table><thead><tr><th>Classification</th><th>Accounts</th></tr></thead><tbody>{stats.cohorts.length?stats.cohorts.map(row=><tr key={row.cohort}><td>{row.cohort.replaceAll('_',' ')}</td><td>{row.accounts}</td></tr>):<tr><td colSpan={2}>No completed accounts yet.</td></tr>}</tbody></table></section></div>
    <section className="dashboard-events"><h2>Recent server facts</h2>{stats.recentEvents.length?<ul className="activity-list">{stats.recentEvents.map((event,i)=><li key={`${event.at}-${i}`}><span>{event.name.replaceAll('_',' ')}</span><time dateTime={event.at}>{new Intl.DateTimeFormat('en-GB',{timeStyle:'short',timeZone:'Europe/Sarajevo'}).format(new Date(event.at))}</time></li>)}</ul>:<p className="small-copy">Completed accounts and credit grants will appear here as they are committed.</p>}</section>
    <details className="metric-definitions"><summary>Definitions & measurement limits</summary><p>The headline counts application completions linked to verified email identities, not visits, typed emails or requested codes. Accounts are not proven unique humans. Selected date filters apply to account completion time; credit totals are current ledger totals for those accounts. Referral counts use the invitee’s completion cohort.</p><p>Staff, test and compensated accounts are excluded by the default Participants filter. Founder-assisted and independent participants remain separately selectable. Client demo completions: {stats.demoCompletions}. Optional demo observations do not indicate verification.</p><p>No visitor conversion percentage is reported because complete consented visitor coverage has not been established. Campaign tags are attribution labels, not proof of physical location. Small, self-selected cohorts do not establish causation.</p></details>
    </>}
    {!judge&&role==='operator'&&<p className="operations-link"><Link href="/admin/operations">Reviews, deletion requests & campaign controls <ArrowUpRight size={15}/></Link></p>}
  </main>;
}
