'use client';
import { useState } from 'react';
import Link from 'next/link';
import useSWR from 'swr';
import { z } from 'zod';
import { request,okSchema } from '@/lib/client';
const queueSchema=z.object({reviews:z.array(z.object({user_id:z.string(),handle:z.string(),cohort:z.string(),completed_at:z.string()})),deletions:z.array(z.object({user_id:z.string(),handle:z.string(),requested_at:z.string(),status:z.string()}))});
export function Operations(){
  const {data,mutate,error}=useSWR('admin/queue',path=>request(path,queueSchema));const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const fields=new FormData(event.currentTarget);const action=String(fields.get('action'));const reason=String(fields.get('reason'));let body:unknown;
    if(action==='pause')body={paused:fields.get('paused')==='true',reason};else if(action==='reverse')body={entryId:fields.get('target'),reason};else if(action==='classify')body={userId:fields.get('target'),cohort:fields.get('cohort'),reason};else if(action==='review')body={userId:fields.get('target'),decision:fields.get('decision'),reason};else body={userId:fields.get('target'),status:fields.get('status'),reason};
    try{await request(`admin/${action}`,okSchema,body);await mutate();setMessage('Change recorded with an audit entry.');}catch(e){setMessage(e instanceof Error?e.message:'Change failed.');}finally{setBusy(false);}}
  return <main id="main" className="operations"><p className="eyebrow">OPERATOR ACCESS</p><h1>Campaign operations.</h1><p>Changes require a sign-in completed in the last 10 minutes and an audit reason. <Link href="/signin">Sign in again</Link></p><p role="status" className="notice">{message||'Review decisions and reversals never silently reopen founding or referral slots.'}</p>{error&&<p className="form-error">Unable to load the queue.</p>}<section><h2>Eligibility review</h2>{data?.reviews.length?data.reviews.map(row=><form key={row.user_id} onSubmit={submit} className="operation-row"><strong>@{row.handle}</strong><input name="action" type="hidden" value="review"/><input name="target" type="hidden" value={row.user_id}/><label>Decision<select name="decision"><option value="eligible">Eligible</option><option value="excluded">Excluded</option></select></label><label>Reason<input name="reason" required minLength={3} maxLength={1000}/></label><button className="button secondary" disabled={busy}>Record decision</button></form>):<p>No accounts awaiting review.</p>}</section><section><h2>Deletion requests</h2>{data?.deletions.length?data.deletions.map(row=><form key={row.user_id} onSubmit={submit} className="operation-row"><strong>@{row.handle} · {row.status}</strong><input name="action" type="hidden" value="deletion"/><input name="target" type="hidden" value={row.user_id}/><label>Status<select name="status"><option value="processing">Processing</option><option value="retention_required">Retention required</option></select></label><label>Handling note<input name="reason" required minLength={3} maxLength={1000}/></label><button className="button secondary" disabled={busy}>Update request</button></form>):<p>No unprocessed deletion requests.</p>}<p className="small-copy">“Completed” is not a shortcut here. Actual erasure follows the documented operator procedure.</p></section>
    <section><h2>Enrollment control</h2><form onSubmit={submit}><input name="action" type="hidden" value="pause"/><label>Campaign status<select name="paused"><option value="true">Pause new enrollment</option><option value="false">Resume reviewed campaign</option></select></label><label>Reason<input name="reason" required minLength={3}/></label><button className="button secondary" disabled={busy}>Apply campaign status</button></form></section>
    <section><h2>Reverse an entitlement</h2><p>This creates an immutable opposite entry. It does not erase history or free a reward slot.</p><form onSubmit={submit}><input name="action" type="hidden" value="reverse"/><label>Credit entry ID<input name="target" required/></label><label>Reason<input name="reason" required minLength={3}/></label><button className="button secondary" disabled={busy}>Record reversal</button></form></section>
    <section><h2>Classify an account</h2><form onSubmit={submit}><input name="action" type="hidden" value="classify"/><label>Account ID<input name="target" required/></label><label>Cohort<select name="cohort"><option value="independent">Independent</option><option value="founder_assisted">Founder-assisted</option><option value="staff">Staff</option><option value="test">Test</option><option value="compensated">Compensated</option></select></label><label>Reason<input name="reason" required minLength={3}/></label><button className="button secondary" disabled={busy}>Record classification</button></form></section><Link href="/admin/validation">Back to validation</Link>
  </main>;
}
