/* Local simulator UI; never included in the production application. */
let transferId=localStorage.getItem('neylo-sandbox-transfer'),pending=JSON.parse(localStorage.getItem('neylo-sandbox-intent')||'null');
const status=document.querySelector('#status'),report=document.querySelector('#report');
async function api(path,body,key){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})}:{},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
const labels={awaiting_funding:'Waiting for simulated funding. Bob has received nothing.',payout_pending:'Funding confirmed. Bob has received nothing yet.',payout_unknown:'Payout outcome unknown. Recover its original reference before doing anything else.',completed:'Simulated bank confirms funds are usable by Bob.',refund_pending:'Payout rejected. Waiting for the simulated refund.',refunded:'Simulated refund confirmed to Alice.'};
async function refresh(){if(!transferId)return;const t=await api('/transfers/'+transferId);status.textContent=labels[t.state];report.textContent=JSON.stringify({transfer:t,reconciliation:await api('/reconciliation')},null,2);document.querySelectorAll('[data-action]').forEach(b=>{const a=b.dataset.action;b.disabled=!(t.state==='awaiting_funding'&&a==='fund'||t.state==='payout_pending'&&['pay','fail','lose-response'].includes(a)||t.state==='payout_unknown'&&a==='recover'||t.state==='refund_pending'&&a==='refund');});}
document.querySelector('#send').addEventListener('submit',async e=>{e.preventDefault();try{const text=document.querySelector('#amount').value.trim().replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(text))throw new Error('Use up to two decimal places.');const [whole,fraction='']=text.split('.');const body={recipient:'@bob',amountMinor:Number(whole)*100+Number(fraction.padEnd(2,'0')),currency:'BAM'};if(!pending||JSON.stringify(pending.body)!==JSON.stringify(body)){pending={key:crypto.randomUUID(),body};localStorage.setItem('neylo-sandbox-intent',JSON.stringify(pending));}const t=await api('/transfers',pending.body,pending.key);transferId=t.id;localStorage.setItem('neylo-sandbox-transfer',transferId);await refresh();}catch(e){status.textContent=e.message;}});
document.querySelector('#controls').addEventListener('click',async e=>{const action=e.target.dataset.action;if(!action||!transferId)return;e.target.disabled=true;try{await api('/simulate',{id:transferId,action});await refresh();}catch(e){status.textContent=e.message;}});
document.querySelector('#new-intent').addEventListener('click',()=>{pending=null;localStorage.removeItem('neylo-sandbox-intent');status.textContent='Next submission creates a separate transfer. Earlier transfers remain recorded.';});
refresh().catch(e=>{status.textContent=e.message;});
