import assert from 'node:assert/strict';
import { readFile,writeFile } from 'node:fs/promises';
import { createClient } from '@supabase/supabase-js';
import { pitchMetricsSchema } from '../src/features/pitch/metrics';
const env=JSON.parse(await readFile('.env.production.secrets.json','utf8'));
assert.equal(env.NEXT_PUBLIC_SUPABASE_URL,'https://tfphopejudgbfrucdxsy.supabase.co');
const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SECRET_KEY,{auth:{persistSession:false}});
const anonymous=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});
const origin=process.argv[2]??'http://127.0.0.1:3102';
assert.ok(['https://neylo.xyz','http://127.0.0.1:3102'].includes(origin));
const checks:string[]=[];
const managed=await db.rpc('neylo_pitch_metrics');assert.equal(managed.error,null);
const authoritative=pitchMetricsSchema.parse(managed.data);
const denied=await anonymous.rpc('neylo_pitch_metrics');assert.ok(denied.error);checks.push('Direct anonymous database function execution denied');
const response=await fetch(origin+'/api/pitch/metrics');assert.equal(response.status,200);
const actual=pitchMetricsSchema.parse(await response.json());
assert.deepEqual({...actual,asOf:''},{...authoritative,asOf:''});checks.push('Public aggregate endpoint exactly matches managed Postgres');
const forged=await fetch(origin+'/api/pitch/metrics?cohort=all&include=email');const fixed=pitchMetricsSchema.parse(await forged.json());assert.deepEqual({...fixed,asOf:''},{...actual,asOf:''});checks.push('Query parameters cannot broaden the public projection');
assert.equal((await fetch(origin+'/api/pitch/metrics',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,405);checks.push('Metrics endpoint rejects writes');
const script=await fetch(origin+'/pitch/script');assert.equal(script.status,200);const words=await script.text();assert.ok(words.includes('Financial execution is simulated'));assert.ok(script.headers.get('Content-Disposition')?.includes('attachment'));checks.push('Complete speaker script downloads with execution boundary');
const page=await fetch(origin+'/pitch');assert.equal(page.status,200);assert.ok((await page.text()).includes('https://neylo.xyz/pitch'));checks.push('Direct pitch navigation and canonical metadata');
assert.equal((await fetch(origin+'/api/admin/accounts')).status,401);checks.push('Private registered-account endpoint remains authenticated');
const report={at:new Date().toISOString(),origin,passed:checks.length,checks,metrics:actual};
await writeFile(`test-results/pitch-${origin.startsWith('https')?'production':'local'}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
